import React, { Component } from 'react';

import './styles.css';

class Title extends Component {

  render() {
    return (
      <div className="Title">
        <h2>
          Have you ever wished to live in the Neverlands forever? Let's forget about adulthood for a moment and enjoy a kid's poem generated by GPT2.
        </h2>
        <h4>You can either jot down a beginning of your own or choose from a collection of cute topics we provide.</h4>
      </div>
    );
  }
}

export default Title;
